name: Build and Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    branches: ["main"]

jobs:

  build:
    name: Building Python Tools ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: windows-latest
            artifact_name: python-env-windows.zip
          # - os: macos-13 # Intel Mac (x64)
          #   artifact_name: python-env-macos-x64.tar.gz
          - os: macos-latest
            artifact_name: python-env-macos-arm64.tar.gz

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.10"
          activate-environment: ogs_python_tools
          environment-file: environment.yml
          channels: conda-forge,nodefaults
      
      - name: Install Requirements
        shell: bash -el {0}
        run: conda install -n base -c conda-forge conda-pack mamba -y
      
      - name: Cleanup Environment
        shell: bash -el {0}
        run: |
          conda clean --all -y
          pip cache purge

      - name: Pack Environment
        shell: bash -el {0}
        run: conda-pack -n base -n ogs_python_tools -o ${{ matrix.artifact_name }}
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_name }}